sudo: false
language: node_js
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
notifications:
  email: false
node_js:
- iojs-v2
- iojs-v1
- '0.12'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_95fb4ca130b1_key -iv $encrypted_95fb4ca130b1_iv
  -in scripts/travis/id_dsa.enc -out ~/.ssh/id_dsa -d
- npm i -g npm@^2.0.0
- npm install -g bower
- bower install
- npm install -g gulp
before_script:
- npm prune
deploy:
  provider: script
  script: scripts/travis/deploy.sh
