sudo: false
language: node_js
services:
- couchdb
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
notifications:
  email: false
node_js:
- iojs-v2
- iojs-v1
- '0.12'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_95fb4ca130b1_key -iv $encrypted_95fb4ca130b1_iv
  -in scripts/travis/id_dsa.enc -out ~/.ssh/id_dsa -d
- npm i -g npm@^2.0.0
- npm install -g bower
- bower install
- npm install -g web-component-tester
- npm install -g gulp
- npm install gulp
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm prune
- curl -Lo travis_after_all.py https://git.io/vLSON
script: npm test
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
- npm run semantic-release
deploy:
  provider: script
  script: scripts/travis/deploy.sh
