sudo: false
language: node_js
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
- couchdb
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
notifications:
  email: false
node_js:
- iojs-v2
- iojs-v1
- '0.12'
- '4.2'
- '5.1'
before_install:
- 'export DISPLAY=:99.0'
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g npm@^2.0.0
- npm i -g bower gulp
- bower install
- npm install -g web-component-tester
- npm prune
- curl -Lo travis_after_all.py https://git.io/vLSON
script: npm test
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
- npm run semantic-release
deploy:
  provider: script
  script: scripts/travis/deploy.sh
