sudo: false
language: node_js
addons:
  firefox: latest
services:
- couchdb
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
notifications:
  email: false
node_js:
- '4.4'
- '5.3'
- '6.0'
before_install:
- 'export DISPLAY=:99.0'
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g npm@^2.0.0
- npm i -g bower gulp
- bower install
- npm install -g web-component-tester
- npm prune
- curl -Lo travis_after_all.py https://git.io/vLSON
script: npm test
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
- npm run semantic-release
deploy:
  provider: script
  script: scripts/travis/deploy.sh
